//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_PR17_restaurant_Balashova.ApplicatonData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        public int ID { get; set; }
        public string naimenov { get; set; }
        public int kolichestvo { get; set; }
        public decimal cena { get; set; }
        public Nullable<int> PostavkiID { get; set; }
        public string komment { get; set; }
        public Nullable<int> ClientID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Postavki Postavki { get; set; }
    }
}
